import type { Metadata } from "next";
import "./globals.css";
import { vasir } from "./fonts";
import { Header } from "@/components/layout/header";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${vasir.className} antialiased bg-black`}>
				<Header />
				{children}
			</body>
		</html>
	);
}
